### ISSUE TITLE
Supporting fonts from system in addition to formulas

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#215]
Different OSes provide different fonts, and our formulas likely cannot ever cover all fonts on all platforms.

Some fonts are licensed for certain platforms only:
- macOS: https://dslabo.blog.fc2.com/blog-entry-2421.html
- Windows

And if people wanted to use those platform-bound fonts in Fontist, they should be given some information:
- Fontist should return a status of "available" if the font is available in the system (for example, a font that is in system but not in formulas, or a manually purchased/installed font)
- Support supplementary font downloads for that particular platform

It seems that there are 4 categories of fonts:
1. Fonts that come with an operating system
2. Fonts that can be dynamically installed on an operating system (e.g. macOS on-demand fonts fontist/formulas#84)
3. Fonts that can be installed as additional software (e.g. Fontist formulas)
4. Fonts that users manually purchase/install

When a user/software requests one of these category of fonts, we should provide them with the best answer.

I wonder what is the best way for Fontist to support these.

**Comment by alexeymorozov** [comment]
Among these categories status of support is:

1. [SUPPORTED] Fonts that come with an operating system
2. [UNSUPPORTED] Fonts that can be dynamically installed on an operating system (e.g. macOS on-demand fonts fontist/formula#86)
3. [PARTLY SUPPORTED] Fonts that can be installed as additional software (e.g. Fontist formulas)
4. [PARTLY SUPPORTED] Fonts that users manually purchase/install

For 3 and 4, I think, we can add directories with those fonts in our system list. And also add a feature to manually add new directories to the list.

For 2, I see several strategies to handle platform-bound fonts:

1. Autogenerate and keep a list of such fonts in fontist, e.g. in formulas with a platform-bound flag
2. Describe platform-bound strategies to detect available to download fonts. E.g. check the MacOS xml, and offer to install them

Cons of 1:
- need to regularly (with new OS version?) update the list

Cons of 2:
- previous versions of OS may lack of some newer fonts, so a user may miss some available fonts

In my opinion, the first one has less drawbacks for a user.

**Comment by ronaldtse** [comment]
Agree, let's go with approach 1 for item 2.

For 3 and 4, agree that a user-managed "font directories" approach is most suitable. For fonts that users install manually, we can assume that most people will install in a directory dedicated on that platform (e.g. `C:\Windows\Fonts` or something like that), so most of the time the user won't need to specifically add a "font directory".

**Comment by alexeymorozov** [comment]
I'll try to generate 1 formula from fontist/formulas#84, and do necessary changes so it would be skipped on other platforms.

**Comment by ronaldtse** [comment]
Makes sense, thanks @alexeymorozov

**Comment by alexeymorozov** [comment]
Finished with the 2 goal in #269. Let's continue with the 1st, or it's enough for now? (It allows to implement fontist/formulas#84, fontist/formulas#85 now)

**Comment by ronaldtse** [comment]
@alexeymorozov let's also attempt 1.

In terms of the categories of fonts on a system, can you update this list?
1. [SUPPORTED] Fonts that come with an operating system
1. [UNSUPPORTED] Fonts that can be dynamically installed on an operating system (e.g. macOS on-demand fonts fontist/formula#86)
1. [PARTLY SUPPORTED] Fonts that can be installed as additional software (e.g. Fontist formulas)
1. [PARTLY SUPPORTED] Fonts that users manually purchase/install

**Comment by alexeymorozov** [comment]
Ok. I think the current status is:

1. [SUPPORTED] Fonts that come with an operating system
2. [PARTLY SUPPORTED] (Can find but cannot install) Fonts that can be dynamically installed on an operating system (e.g. macOS on-demand fonts fontist/formula#86)
3. [SUPPORTED] (If installed in a system or fontist directory) Fonts that can be installed as additional software (e.g. Fontist formulas)
4. [SUPPORTED] (If installed in a system directory) Fonts that users manually purchase/install

**Comment by alexeymorozov** [comment]
When some on-demand font is requested to install we can offer to download it manually and provide instructions on how to do it.

To implement this we can create custom formulas which would contain:

- instructions on how to install these fonts
- font family and subfamily names (for search)

And this formula wouldn't contain any (since there are not necessary):

- urls for downloading
- license for installation

**Comment by alexeymorozov** [comment]
Such formula could look like this:

```yaml
---
description: Fonts available for download in Catalina
homepage: https://support.apple.com/en-us/HT210192#download
instructions: |-
  To download and enable any of these fonts:

  1. Open Font Book, which is in your Applications folder. 
  2. Select All Fonts in the sidebar, or use the Search field to find the font that you want to download. Fonts that aren't already downloaded appear dimmed in the list of fonts. 
  3. Select the dimmed font and choose Edit > Download, or Control-click it and choose Download from the pop-up menu.
fonts:
- name: Apple LiGothic
  styles:
  - family_name: Apple LiGothic
    type: Medium
    full_name: Apple LiGothic Medium
    post_script_name: LiGothicMed
    version: '13.0d2e6'
    copyright: Apple Computer, Inc. 1992-1998
    font: AppleLiGothic-Medium.ttf
```
