### ISSUE TITLE
Arial, Arial Narrow and Arial Black

### ISSUE THREAD

**Issue by Intelligent2013** [fontist/fontist#247]
Source issue: https://github.com/metanorma/bipm-si-brochure/issues/143
Currently, fontist_locations.yml:
```yaml
---
Arial:
  Regular:
    full_name: Arial
    paths:
    - C:/Windows/Fonts/arial.ttf
  Bold:
    full_name: Arial Bold
    paths:
    - C:/Windows/Fonts/arialbd.ttf
  Bold Italic:
    full_name: Arial Bold Italic
    paths:
    - C:/Windows/Fonts/arialbi.ttf
  Italic:
    full_name: Arial Italic
    paths:
    - C:/Windows/Fonts/ariali.ttf
  Narrow:
    full_name: Arial Narrow
    paths:
    - C:/Windows/Fonts/ARIALN.TTF
  Narrow Bold:
    full_name: Arial Narrow Bold
    paths:
    - C:/Windows/Fonts/ARIALNB.TTF
  Narrow Bold Italic:
    full_name: Arial Narrow Bold Italic
    paths:
    - C:/Windows/Fonts/ARIALNBI.TTF
  Narrow Italic:
    full_name: Arial Narrow Italic
    paths:
    - C:/Windows/Fonts/ARIALNI.TTF
  Black:
    full_name: Arial Black
    paths:
    - C:/Windows/Fonts/ariblk.ttf
```

but Arial, Arial Narrow and Arial Black are different fonts (font's modifications), but not a styles for one font Arial:
![image](https://user-images.githubusercontent.com/5559926/124581717-03f8ec00-de5a-11eb-94c0-0aa5e26c1b25.png)

So, fontist locations should be:
```yaml
---
Arial:
  Regular:
    full_name: Arial
    paths:
    - C:/Windows/Fonts/arial.ttf
  Bold:
    full_name: Arial Bold
    paths:
    - C:/Windows/Fonts/arialbd.ttf
  Bold Italic:
    full_name: Arial Bold Italic
    paths:
    - C:/Windows/Fonts/arialbi.ttf
  Italic:
    full_name: Arial Italic
    paths:
    - C:/Windows/Fonts/ariali.ttf
Arial Narrow:
  Regular:
    full_name: Arial Narrow
    paths:
    - C:/Windows/Fonts/ARIALN.TTF
  Narrow Bold:
    full_name: Arial Narrow Bold
    paths:
    - C:/Windows/Fonts/ARIALNB.TTF
  Narrow Bold Italic:
    full_name: Arial Narrow Bold Italic
    paths:
    - C:/Windows/Fonts/ARIALNBI.TTF
  Narrow Italic:
    full_name: Arial Narrow Italic
    paths:
    - C:/Windows/Fonts/ARIALNI.TTF
Arial Black:
  Regular:
    full_name: Arial Black
    paths:
    - C:/Windows/Fonts/ariblk.ttf
```

**Comment by alexeymorozov** [comment]
This font contains the following info:

```
$ otfinfo -i ARIALNBI.TTF
Family:              Arial Narrow
Subfamily:           Bold Italic

Preferred family:    Arial
Preferred subfamily: Narrow Bold Italic
```

Currently fontist uses "Preferred" attributes if they exist. For some fonts the "Preferred" attributes provide better separation. That's why it occured in the Arial font.

I see two ways to fix it:

1. If there is no real use case to use the "Preferred" attribute, fontist can always use the default attribute
2. Add fonts to both groups: "Arial" and "Arial Narrow"

Do we know any use case for the Preferred attribute?

**Comment by ronaldtse** [comment]
From Microsoft: 

https://docs.microsoft.com/en-us/typography/opentype/spec/name

> For extended typographic families that includes fonts other than the four basic styles (regular, italic, bold, bold italic), it is strongly recommended that name IDs 16 and 17 be used in fonts to create an extended, typographic grouping. (See examples provided below.) 
> 
> It is also strongly recommended that applications support extended typographic-family groupings using name IDs 16 and 17. Note, in particular, that variable fonts can include a large number of named instances, each of which will use a shared typographic family name (name ID 16) and will have a typographic subfamily name (equivalent to name ID 17). Applications that assume a four-style family grouping based on name IDs 1 and 2 are likely to provide a poor user experience with variable fonts. 
> 
> For fonts within an extended typographic family that fall outside the basic four-way distinction, the distinguishing attributes should be reflected in the Font Family name so that those fonts appear as a separate font family. For example, the Font Family name for the Arial Narrow font is “Arial Narrow”; the Font Family name for the Arial Black font is “Arial Black”. Note that, in such cases, name ID 16 should also be included with a shared name that reflects the full, typographic family

.

**Comment by ronaldtse** [comment]
This means that the intended way of doing the font is to have "preferred family" > "preferred subfamily". But because many applications expect a "family" to only include the 4 styles (regular, bold, italics, bold italics), we should support both.

The intended hierarchy is:

* Arial (family)
  * {blank} (family)
    * Bold (style)
  * Arial Narrow (family)
    * Bold (style)

In this case, I think the best approach is:
* Treat "family" as a separate font family. Then "Arial Narrow" is considered a separate family from "Arial".
* Add a link from "Arial Narrow" to "Arial"  (or provide two hierarchies - one that is based on the simple "family -> subfamily", and another one that is based on "preferred family -> preferred subfamily") and use a Fontist option to select which to use.
*

**Comment by alexeymorozov** [comment]
fontist v1.10.0 is released. Should help with the Arial Narrow issue.

This update helps with system or already installed fonts. The next work is to update fontist formulas, so they can be installed by Family instead of Preferred Family too.

**Comment by Intelligent2013** [comment]
> fontist v1.10.0 is released. Should help with the Arial Narrow issue.

Issue with Arial Narrow solved. But there is a new issue with fonts 'Work Sans'. I've tried to generate PDF for BIPM brochure, but cover page rendered with wrong fonts.

@ronaldtse do we need to add the `--preferred-family` into metanorma gem?

Previous version fontist location yml file (generated from metanorma gem) contained Black, Medium, Bold, ExtraBold, etc.:
```yaml
Work Sans:
  Black:
    full_name: Work Sans Black
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-Black.ttf
  Black Italic:
    full_name: Work Sans Black Italic
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-BlackItalic.ttf
  Bold:
    full_name: Work Sans Bold
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-Bold.ttf
  Bold Italic:
    full_name: Work Sans Bold Italic
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-BoldItalic.ttf
  ExtraBold:
    full_name: Work Sans ExtraBold
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-ExtraBold.ttf
  ExtraBold Italic:
    full_name: Work Sans ExtraBold Italic
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-ExtraBoldItalic.ttf
  ExtraLight:
    full_name: Work Sans ExtraLight
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-ExtraLight.ttf
  ExtraLight Italic:
    full_name: Work Sans ExtraLight Italic
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-ExtraLightItalic.ttf
  Italic:
    full_name: Work Sans Italic
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-Italic.ttf
  Light:
    full_name: Work Sans Light
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-Light.ttf
  Light Italic:
    full_name: Work Sans Light Italic
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-LightItalic.ttf
  Medium:
    full_name: Work Sans Medium
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-Medium.ttf
  Medium Italic:
    full_name: Work Sans Medium Italic
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-MediumItalic.ttf
  Regular:
    full_name: Work Sans Regular
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-Regular.ttf
  SemiBold:
    full_name: Work Sans SemiBold
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-SemiBold.ttf
  SemiBold Italic:
    full_name: Work Sans SemiBold Italic
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-SemiBoldItalic.ttf
  Thin:
    full_name: Work Sans Thin
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-Thin.ttf
  Thin Italic:
    full_name: Work Sans Thin Italic
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-ThinItalic.ttf
```

Current version (v.1.10.0) fontist location yml file (generated from metanorma gem) contains only Bold, Italic and Regular:
```yaml
Work Sans:
  Bold:
    full_name: Work Sans Bold
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-Bold.ttf
  Bold Italic:
    full_name: Work Sans Bold Italic
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-BoldItalic.ttf
  Italic:
    full_name: Work Sans Italic
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-Italic.ttf
  Regular:
    full_name: Work Sans Regular
    paths:
    - C:/Users/UserTest/.fontist/fonts/WorkSans-Regular.ttf
```

you can compare two versions:
old: [fontist_locations20210705.txt](https://github.com/fontist/fontist/files/6851187/fontist_locations20210705.txt)
new: [fontist_locations20210720.txt](https://github.com/fontist/fontist/files/6851191/fontist_locations20210720.txt)

Generated PDF has wrong fonts on cover page:
New cover page (one font used - Regular):
![image](https://user-images.githubusercontent.com/5559926/126395041-f27a821e-767e-489d-8848-2ddc539575c1.png)

Old cover page (four fonts used - Thin, Light, ExtraLight and Regular):
![image](https://user-images.githubusercontent.com/5559926/126395016-16dbd7cc-7397-4d92-95db-6817e116afba.png)


To generate PDF:
```
git clone https://github.com/metanorma/bipm-si-brochure/
bundle update
bundle exec metanorma -t bipm -x pdf sources/si-brochure-en.adoc
```
you can catch generated fontist locations yml in temporary path while PDF is generating:
```
java -Xss5m -Xmx2048m -jar C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mn2pdf-1.34/lib/../bin/mn2pdf.jar --xml-file "sources/si-brochure-en.presentation.xml" --xsl-file "C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-bipm-1.1.5.1/lib/isodoc/bipm/bipm.brochure.xsl" --pdf-file "sources/si-brochure-en.pdf" --font-manifest C:/Users/UserTest/AppData/Local/Temp/fontist_locations20210721-3092-8rcaw6.yml
```
here: `C:/Users/UserTest/AppData/Local/Temp/fontist_locations20210721-3092-8rcaw6.yml`
