### ISSUE TITLE
Install Microsoft Vista fonts

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#3]
Fonts:
```yaml
meiryo.ttf: Meiryo.ttf
meiryoi.ttf: Meiryo Italic.ttf
meiryoui.ttf: Meiryo UI.ttf
meiryouii.ttf: Meiryo UI Italic.ttf
meiryob.ttf: Meiryo Bold.ttf
meiryoz.ttf: Meiryo Bold Italic.ttf
meiryouib.ttf: Meiryo UI Bold.ttf
meiryouiz.ttf: Meiryo UI Bold Italic.ttf
calibri.ttf: Calibri.ttf
calibrib.ttf: Calibri Bold.ttf
calibrii.ttf: Calibri Italic.ttf
calibriz.ttf: Calibri Bold Italic.ttf
cambriab.ttf: Cambria Bold.ttf
cambriai.ttf: Cambria Italic.ttf
cambriaz.ttf: Cambria Bold Italic.ttf
candara.ttf: Candara.ttf
candarab.ttf: Candara Bold.ttf
candarai.ttf: Candara Italic.ttf
candaraz.ttf: Candara Bold Italic.ttf
consola.ttf: Consola.ttf
consolab.ttf: Consola Bold.ttf
consolai.ttf: Consola Italic.ttf
consolaz.ttf: Consola Bold Italic.ttf
constan.ttf: Constantia.ttf
constanb.ttf: Constantia Bold.ttf
constani.ttf: Constantia Italic.ttf
constanz.ttf: Constantia Bold Italic.ttf
corbel.ttf: Corbel.ttf
corbelb.ttf: Corbel Bold.ttf
corbeli.ttf: Corbel Italic.ttf
corbelz.ttf: Corbel Bold Italic.ttf

cambria.ttc: "Cambria" "Cambria Math"
meiryo.ttc: "Meiryo" "Meiryo Italic" "Meiryo UI" "Meiryo UI Italic"
meiryob.ttc: "Meiryo Bold" "Meiryo Bold Italic" "Meiryo UI Bold" "Meiryo UI Bold Italic"
```

macOS:
```
# Install cabextract
brew install cabextract
# Install Microsoft Vista fonts
export RENAME_FONTS=false
curl -Ls https://raw.githubusercontent.com/fontist/vista-fonts-installer/master/vista-fonts-installer.sh | bash
```

Ubuntu:
```
sudo apt-get -y install cabextract
# Setup Cambria fonts
curl -Ls https://raw.githubusercontent.com/fontist/vista-fonts-installer/master/vista-fonts-installer.sh | sudo bash
```
