### ISSUE TITLE
 Ruby 3.2 unrecognized option: max_redirects

### ISSUE THREAD

**Issue by CAMOBAP** [fontist/fontist#317]
This issue appears before but disappear now it happens again

```
1) Fontist::Utils::Downloader.download file has no extension uses content-type to detect extension
     Failure/Error:
       m.call(*args).tap do |file|
         allow(file).to receive(:original_filename)
           .and_return("no_ext_filename")
         allow(file).to receive(:content_type)
           .and_return("application/zip")
       end

     ArgumentError:
       unrecognized option: max_redirects
     # ./vendor/bundle/ruby/3.2.0/gems/down-5.4.0/lib/down/net_http.rb:145:in `open_uri'
     # ./vendor/bundle/ruby/3.2.0/gems/down-5.4.0/lib/down/net_http.rb:94:in `download'
     # ./vendor/bundle/ruby/3.2.0/gems/down-5.4.0/lib/down/backend.rb:13:in `download'
     # ./vendor/bundle/ruby/3.2.0/gems/down-5.4.0/lib/down.rb:10:in `download'
     # ./spec/fontist/utils/downloader_spec.rb:84:in `call'
     # ./spec/fontist/utils/downloader_spec.rb:84:in `block (6 levels) in <top (required)>'
     # ./lib/fontist/utils/downloader.rb:81:in `do_download_file_with_progress_bar'
     # ./lib/fontist/utils/downloader.rb:66:in `do_download_file'
     # ./lib/fontist/utils/downloader.rb:56:in `download_file'
     # ./lib/fontist/utils/downloader.rb:24:in `block in download'
     # ./lib/fontist/utils/cache.rb:14:in `fetch'
     # ./lib/fontist/utils/downloader.rb:[23](https://github.com/fontist/fontist/actions/runs/4307648281/jobs/7512974848#step:5:24):in `download'
     # ./lib/fontist/utils/downloader.rb:8:in `download'
     # ./spec/fontist/utils/downloader_spec.rb:92:in `block (5 levels) in <top (required)>'
     # ./spec/support/fontist_helper.rb:340:in `block in avoid_cache'
     # ./spec/support/fontist_helper.rb:[33](https://github.com/fontist/fontist/actions/runs/4307648281/jobs/7512974848#step:5:34)5:in `avoid_cache'
     # ./spec/fontist/utils/downloader_spec.rb:82:in `block (4 levels) in <top (required)>'
```

https://github.com/janko/down/issues/82 - was reported but it cannot be reproduced
